/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.projeto.individual;

import java.awt.Image;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Samuel Junior
 */
public class Tela extends javax.swing.JFrame {
     Integer menorNumero = 0, maiorNumero = 0, contador = 0;
     Integer minCpu, minDisco, minMemoria;
     Integer maxvalorCput, maxvalorDisco, maxvalorMemoria;
     Double totalCpu =0.0, totalDisco=0.0, totalMemoria=0.0;
      Double mediavalorCpu, mediavalordisco, mediavalormemoria;
      Random numeroRandomico = new Random();
     
      
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        disco = new javax.swing.JLabel();
        minLabelCpu = new javax.swing.JLabel();
        memoria = new javax.swing.JLabel();
        mediaDisco = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        maxMemoria = new javax.swing.JLabel();
        porcentagemCpu = new javax.swing.JLabel();
        porcentagemMemoria = new javax.swing.JLabel();
        porcentagemDisco = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        cpu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mediaCpu = new javax.swing.JLabel();
        maxCpu = new javax.swing.JLabel();
        minLabelDisco = new javax.swing.JLabel();
        maxDisco = new javax.swing.JLabel();
        minLabelMemoria = new javax.swing.JLabel();
        mediaMemoria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setForeground(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 204, 204));

        disco.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samuel Junior\\Documents\\NetBeansProjects\\projeto-individual\\src\\main\\java\\br\\com\\bandtec\\projeto\\individual\\disco.jpeg")); // NOI18N
        disco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        minLabelCpu.setForeground(new java.awt.Color(0, 0, 0));
        minLabelCpu.setText("Min");

        memoria.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samuel Junior\\Documents\\NetBeansProjects\\projeto-individual\\src\\main\\java\\br\\com\\bandtec\\projeto\\individual\\memoria.jpeg")); // NOI18N
        memoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        mediaDisco.setForeground(new java.awt.Color(0, 0, 0));
        mediaDisco.setText("Média");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("Rodar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        maxMemoria.setForeground(new java.awt.Color(0, 0, 0));
        maxMemoria.setText("Max");

        jProgressBar1.setBackground(new java.awt.Color(51, 255, 0));
        jProgressBar1.setForeground(new java.awt.Color(0, 0, 0));
        jProgressBar1.setStringPainted(true);

        jProgressBar2.setBackground(new java.awt.Color(102, 255, 0));
        jProgressBar2.setForeground(new java.awt.Color(0, 0, 0));
        jProgressBar2.setStringPainted(true);

        jProgressBar3.setBackground(new java.awt.Color(51, 255, 0));
        jProgressBar3.setForeground(new java.awt.Color(0, 0, 0));
        jProgressBar3.setStringPainted(true);

        cpu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samuel Junior\\Documents\\NetBeansProjects\\projeto-individual\\src\\main\\java\\br\\com\\bandtec\\projeto\\individual\\cpu.jpeg")); // NOI18N
        cpu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CPU");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("DISCO");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("MEMORIA");

        mediaCpu.setForeground(new java.awt.Color(0, 0, 0));
        mediaCpu.setText("Média:");

        maxCpu.setForeground(new java.awt.Color(0, 0, 0));
        maxCpu.setText("Max");

        minLabelDisco.setForeground(new java.awt.Color(0, 0, 0));
        minLabelDisco.setText("Min");

        maxDisco.setForeground(new java.awt.Color(0, 0, 0));
        maxDisco.setText("Max:");

        minLabelMemoria.setForeground(new java.awt.Color(0, 0, 0));
        minLabelMemoria.setText("Min");

        mediaMemoria.setForeground(new java.awt.Color(0, 0, 0));
        mediaMemoria.setText("Média");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(226, 226, 226)
                .addComponent(jLabel6)
                .addGap(126, 126, 126))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(porcentagemCpu))
                            .addComponent(cpu, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(minLabelCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mediaCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(minLabelDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mediaDisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(porcentagemDisco)
                                        .addContainerGap(334, Short.MAX_VALUE))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(maxDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(maxMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(disco)
                                .addGap(89, 89, 89)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(minLabelMemoria)
                                        .addGap(43, 43, 43)
                                        .addComponent(mediaMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(memoria, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 375, Short.MAX_VALUE)
                        .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(porcentagemMemoria)
                        .addGap(37, 37, 37))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(memoria))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(26, 26, 26)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(disco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porcentagemCpu)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porcentagemDisco)
                    .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porcentagemMemoria))
                .addGap(95, 95, 95)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mediaDisco)
                    .addComponent(minLabelCpu)
                    .addComponent(maxMemoria)
                    .addComponent(mediaCpu)
                    .addComponent(maxCpu)
                    .addComponent(minLabelDisco)
                    .addComponent(maxDisco)
                    .addComponent(minLabelMemoria)
                    .addComponent(mediaMemoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Integer numeroCpuSorteado = numeroRandomico.nextInt(101);
        Integer numeroDiscoSortado = numeroRandomico.nextInt(101);
        Integer numeroMemoriaSorteado = numeroRandomico.nextInt(101);
        
        contador+=1;
        totalCpu += numeroCpuSorteado;
        totalDisco+= numeroDiscoSortado;
        totalMemoria+= numeroMemoriaSorteado;
        
        if(contador == 1){
            minCpu = numeroCpuSorteado;
            minDisco = numeroDiscoSortado;
            minMemoria = numeroMemoriaSorteado;
            maxvalorCput = numeroCpuSorteado;
            maxvalorDisco = numeroDiscoSortado;
            maxvalorMemoria = numeroMemoriaSorteado;
          
        }
        else{
            if(minCpu>= numeroCpuSorteado){
                minCpu = numeroCpuSorteado;
            }
            if(minDisco>= numeroDiscoSortado){
                minDisco = numeroDiscoSortado;
            }
            if(minMemoria>=numeroMemoriaSorteado){
                minMemoria = numeroMemoriaSorteado;
            }
            
            if(numeroCpuSorteado>= maxvalorCput){
                maxvalorCput = numeroCpuSorteado;
            }
            if(numeroDiscoSortado>=maxvalorDisco){
                maxvalorDisco = numeroDiscoSortado;
            }
            if(numeroMemoriaSorteado>=maxvalorMemoria){
                maxvalorMemoria = numeroMemoriaSorteado;
            }
            
        }
        mediavalorCpu = Double.valueOf(totalCpu/contador);
        mediavalordisco = Double.valueOf(totalDisco/contador);
        mediavalormemoria = Double.valueOf(totalMemoria/contador);
        
        minLabelCpu.setText("Min: "+minCpu.toString());
        minLabelDisco.setText("Min: "+minDisco.toString());
        minLabelMemoria.setText("Min: "+minMemoria.toString());
        
        mediaCpu.setText("Média: "+ String.format("%.2f", mediavalorCpu));
        mediaDisco.setText("Média: "+String.format("%.2f", mediavalordisco));
        mediaMemoria.setText("Média:"+String.format("%.2f", mediavalormemoria));
        
        maxCpu.setText("Max: "+maxvalorCput.toString());
        maxDisco.setText("Max: "+maxvalorDisco.toString());
        maxMemoria.setText("Max: "+maxvalorMemoria.toString());

        jProgressBar1.setValue(numeroCpuSorteado);
        porcentagemCpu.setText(String.valueOf(numeroCpuSorteado)+"%");

        jProgressBar2.setValue(numeroDiscoSortado);
        porcentagemDisco.setText(String.valueOf(numeroDiscoSortado)+"%");

        
        jProgressBar3.setValue(numeroMemoriaSorteado);
        porcentagemMemoria.setText(String.valueOf(numeroMemoriaSorteado)+"%");
                
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cpu;
    private javax.swing.JLabel disco;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel maxCpu;
    private javax.swing.JLabel maxDisco;
    private javax.swing.JLabel maxMemoria;
    private javax.swing.JLabel mediaCpu;
    private javax.swing.JLabel mediaDisco;
    private javax.swing.JLabel mediaMemoria;
    private javax.swing.JLabel memoria;
    private javax.swing.JLabel minLabelCpu;
    private javax.swing.JLabel minLabelDisco;
    private javax.swing.JLabel minLabelMemoria;
    private javax.swing.JLabel porcentagemCpu;
    private javax.swing.JLabel porcentagemDisco;
    private javax.swing.JLabel porcentagemMemoria;
    // End of variables declaration//GEN-END:variables
    
}
